---
- include_tasks: clean_op_tags.yml
  tags: clean_op_tags
  when: ansible_distribution_major_version == "7"

- include_tasks: judge_op_tags.yml
  tags: judge_op_tags
  when: ansible_distribution_major_version == "7"

- include_tasks: init_dir.yml
  tags: init_dir

- include_tasks: set_yum.yml
  tags: set_yum
  when: ansible_distribution_major_version == "7" 

- include_tasks: yum_package.yml
  tags: yum_package
  when: ansible_distribution_major_version == "7" 

- include_tasks: set_system.yml
  tags: set_system
  when: ansible_distribution_major_version == "7"

