---
- name: Setting resolv.conf
  shell: |
    cat > /etc/resolv.conf < EOF
    nameserver 119.29.29.29
    nameserver 223.5.5.5
    EOF

- name: Modify i18n
  shell: |
    echo 'LANG="en_US.UTF-8"' >/etc/sysconfig/i18n
    source /etc/sysconfig/i18n

- name: Modify limit.conf
  shell: |
    cat >> /etc/security/limits.conf << EOF
    *           soft   nofile       65535
    *           hard   nofile       65535
    EOF

- name: Modify sshd_config
  shell: |
    \cp /etc/ssh/sshd_config /etc/ssh/sshd_config.`date +"%Y-%m-%d_%H-%M-%S"`
    sed -i 's/^GSSAPIAuthentication yes$/GSSAPIAuthentication no/' /etc/ssh/sshd_config
    sed -i 's/#UseDNS yes/UseDNS no/' /etc/ssh/sshd_config
    sed -i 's%#PermitEmptyPasswords no%PermitEmptyPasswords no%g' /etc/ssh/sshd_config
    /etc/init.d/sshd restart

- name: Modefy sysctl.conf
  shell: |
    cat >> /etc/sysctl.conf << EOF
    net.ipv4.tcp_tw_recycle = 1
    net.ipv4.tcp_tw_reuse = 1
    net.ipv4.ip_local_port_range = 10000 65000
    net.ipv4.tcp_syncookies = 1
    net.ipv4.tcp_max_tw_buckets = 36000
    net.ipv4.tcp_max_syn_backlog = 16384
    net.ipv4.tcp_keepalive_time = 600
    net.ipv4.tcp_fin_timeout = 30
    vm.swappiness=1
    vm.max_map_count = 262144
    EOF

- name: Modify profile
  shell: echo 'export PS1="[ \033[01;33m\u\033[0;36m@\033[01;34m\h \033[01;31m\w\033[0m ]\033[0m \n#"' >> /etc/profile

- name: Modify .vimrc
    cat >> /root/.vimrc << EOF
    syntax enable
    syntax on
    set ruler
    set number
    set cursorline
    set cursorcolumn
    set hlsearch
    set incsearch
    set ignorecase
    set nocompatible
    set wildmenu
    set paste
    set expandtab
    set tabstop=2
    set shiftwidth=4
    set softtabstop=4
    set gcr=a:block-blinkon0
    set guioptions-=l
    set guioptions-=L
    set guioptions-=r
    set guioptions-=R
    highlight CursorLine   cterm=NONE ctermbg=black ctermfg=green guibg=NONE guifg=NONE
    highlight CursorColumn cterm=NONE ctermbg=black ctermfg=green guibg=NONE guifg=NONE
    EOF

- name: Modify crond
    cat >> /var/spool/cron/root << EOF
    MAILTO=''
    */10 * * * * /usr/sbin/ntpdate ntp1.aliyun.com  2.cn.pool.ntp.org > /dev/null 2>&1
    EOF

- name: Modify fail2ban jail.conf
  copy:
    src: jain.conf
    dest: /etc/fail2ban/jail.conf
    mode: "0644"
