---
- name: Yum Basic Package
  yum:
    name: "{{ package }}"
  packages:
    - autoconf
    - bison
    - bitmap-fonts
    - bridge-utils
    - bzip2
    - bzip2-devel
    - cmake
    - curl
    - curl-devel
    - cyrus-sasl
    - cyrus-sasl-devel
    - dos2unix
    - dstat
    - e2fsprogs
    - e2fsprogs-devel
    - fail2ban
    - flex
    - fontconfig
    - fontconfig-devel
    - freetype
    - freetype-deve
    - freetype-devel
    - gcc
    - gcc-c++
    - gd-devel
    - ghostscript
    - ghostscript-devel
    - glances
    - glib2
    - glib2-devel
    - glibc
    - glibc-devel
    - glusterfs
    - glusterfs-fuse
    - gmp-devel
    - gperf
    - htop
    - iftop
    - iotop
    - iptraf
    - krb5-devel
    - krb5-libs
    - libcurl-devel
    - libfontenc
    - libiconv
    - libffi-devel
    - libicu-devel
    - libjpeg
    - libjpeg-devel
    - libjpeg-turbo-devel
    - libmcrypt
    - libmcrypt-devel
    - libpng
    - libpng-devel
    - libtidy*
    - libtool-ltdl-devel
    - libXfont
    - libxml2
    - libxml2-devel
    - libxslt-devel
    - lrzsz
    - make
    - mcrypt
    - mhash
    - mhash-devel
    - ncurses
    - ncurses-devel
    - nethogs
    - nfs-utils
    - nmap
    - ntp
    - oniguruma-devel
    - OpenIPMI-tools
    - openldap
    - openldap-clients
    - openldap-devel
    - openldap-servers
    - openssl
    - openssl-devel
    - pcre
    - pcre-devel
    - perl-devel
    - psmisc
    - re2c
    - readline-devel
    - ruby
    - screen
    - sqlite-devel
    - strace
    - sysstat
    - tcpdump
    - telnet
    - tree
    - urw-fonts
    - vim
    - wget
    - xorg-x11-fonts-base
    - xorg-x11-fonts-Type1
    - xorg-x11-font-utils
    - yasm
    - zlib
    - zlib-devel
