---
- name: turn on cluster
  replace:
    path: "{{ kafka_conf_dir }}/kafka-{{ kafka_port }}.conf"
    regexp: "^#cluster"
    replace: cluster
  tags: turn_on_cluster

- name: turn off cluster
  replace:
    path: "{{ kafka_conf_dir }}/kafka-{{ kafka_port }}.conf"
    regexp: "^cluster"
    replace: "#cluster"
  tags: turn_off_cluster
