#创建connector实例的命令：
curl -i http://10.97.138.195:8083/connectors -X POST -H "Content-Type: application/json" --data '{"name":"lcy1-tb_entity_test","config":{"connector.class": "io.debezium.connector.mysql.MySqlConnector","database.hostname": "10.97.138.195","database.port": "3306","database.user": "root","database.password": "I.lw@2020","database.server.id": "1044","database.server.name": "lcy1","database.whitelist": "db_entities_relations","table.whitelist": "db_entities_relations.tb_entity_test","database.history.kafka.bootstrap.servers": "10.97.138.195:9092","database.history.kafka.topic": "lcy1_tb_entity_test.history","include.schema.changes": "true","decimal.handling.mode": "string","database.serverTimezone": "UTC","bigint.unsigned.handling.mode": "long","max.request.size": "50000000","time.precision.mode": "connect","database.history.store.only.monitored.tables.ddl":"true","database.history.skip.unparseable.ddl":"true","name": "lcy1-tb_entity_test"}}'

目标connector实例1：
{"name":"cms-connector-es","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.138.130","database.port":"5575","database.user":"root","database.password":"SQL@ynzy2020","database.server.id":"1301302","database.server.name":"cms","database.whitelist":"cms_management","table.whitelist":"cms_management.tb_init_article","database.history.kafka.bootstrap.servers":"10.97.138.195:9092 ","database.history.kafka.topic":"mxj.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"cms-connector-es"},"tasks":[{"connector":"cms-connector-es","task":0}],"type":"source"}

实例1报错：
{"name":"cms-connector-es","connector":{"state":"RUNNING","worker_id":"127.0.0.1:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"127.0.0.1:8083","trace":"io.debezium.DebeziumException: The connector is trying to read binlog starting at SourceInfo [currentGtid=null, currentBinlogFilename=mysql-bin.000001, currentBinlogPosition=169113462, currentRowNumber=0, serverId=0, sourceTime=null, threadId=-1, currentQuery=null, tableIds=[], databaseName=null], but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.\n\tat io.debezium.connector.mysql.MySqlConnectorTask.validateSnapshotFeasibility(MySqlConnectorTask.java:325)\n\tat io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:94)\n\tat io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"}],"type":"source"}[root@localhost ~]#

目标connector实例2：
欧阳需要的是cms_management.tb_contribution
{"name":"cms-connector","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.138.130","database.port":"5575","database.user":"root","database.password":"SQL@ynzy2020","database.server.id":"1301301","database.server.name":"cms","database.whitelist":"cms_management","table.whitelist":"cms_management.tb_contribution","database.history.kafka.bootstrap.servers":"10.97.138.195:9092 ","database.history.kafka.topic":"mxj.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"cms-connector"},"tasks":[{"connector":"cms-connector","task":0}],"type":"source"}
实例2报错：
{"name":"cms-connector","connector":{"state":"RUNNING","worker_id":"127.0.0.1:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"127.0.0.1:8083","trace":"org.apache.kafka.connect.errors.ConnectException: Unrecoverable exception from producer send callback\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.maybeThrowProducerSendException(WorkerSourceTask.java:282)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:336)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:264)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.common.errors.RecordTooLargeException: The message is 2060218 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.\n"}],"type":"source"}
实列2启动：
curl -i http://10.97.138.195:8083/connectors -X POST -H "Content-Type: application/json" --data '{"name":"cms-connector","config":{"connector.class": "io.debezium.connector.mysql.MySqlConnector","database.hostname": "10.97.138.130","database.port": "5575","database.user": "root","database.password": "SQL@ynzy2020","database.server.id": "1301301","database.server.name": "cms","database.whitelist": "cms_management","table.whitelist": "cms_management.tb_contribution","database.history.kafka.bootstrap.servers": "10.97.138.195:9092","database.history.kafka.topic": "mxj.history","include.schema.changes": "true","decimal.handling.mode": "string","database.serverTimezone": "UTC","bigint.unsigned.handling.mode": "long","max.request.size": "50000000","time.precision.mode": "connect","database.history.store.only.monitored.tables.ddl":"true","database.history.skip.unparseable.ddl":"true","name": "cms-connector","producer.override.max.request.size": "52428800","broker.override.message.max.bytes": "52428800","consumer.override.fetch.message.max.bytes": "52428800"}}'

producer.override.max.request.size=52428800
broker.override.message.max.bytes=52428800
consumer.override.fetch.message.max.bytes=52428800


#138.195上运行的cdc实例：
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/
["lcy-tb_entity_relation_test","login-user-connector","bu-member-connector","catalog-connector","cms-connector-es","org-info-connector","lcy1-tb_entity_test","mysql","mxj-er-tie","mxj-connector","bu-member-sponsor-connector"][root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/lcy-tb_entity_relation_test
{"name":"lcy-tb_entity_relation_test","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.138.195","database.port":"3306","database.user":"root","database.password":"I.lw@2020","database.server.id":"145","database.server.name":"lcy","database.whitelist":"db_entities_relations","table.whitelist":"db_entities_relations.tb_entity_relation_test","database.history.kafka.bootstrap.servers":"10.97.138.195:9092","database.history.kafka.topic":"lcy-tb_entity_relation_test.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"lcy-tb_entity_relation_test"},"tasks":[{"connector":"lcy-tb_entity_relation_test","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/login-user-connector
{"name":"login-user-connector","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.149.9","database.port":"5575","database.user":"root","database.password":"Mysql@ynzy2021","database.server.id":"149901","database.server.name":"db_zy_manager","database.whitelist":"db_zy_manager","table.whitelist":"db_zy_manager.tb_manager_login_user","database.history.kafka.bootstrap.servers":"10.97.138.195:9092","database.history.kafka.topic":"login-user.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"login-user-connector"},"tasks":[{"connector":"login-user-connector","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/bu-member-connector
{"name":"bu-member-connector","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.149.9","database.port":"5575","database.user":"root","database.password":"Mysql@ynzy2021","database.server.id":"130136","database.server.name":"mem_cdc","database.whitelist":"db_mem_member_info,db_mem_entities_relations","table.whitelist":"db_mem_member_info.tb_member_points,db_mem_member_info.tb_member_info,db_mem_entities_relations.tb_entity,db_mem_entities_relations.tb_entity_relation","database.history.kafka.bootstrap.servers":"10.97.138.195:9092","database.history.kafka.topic":"mem_cdc.member_database_history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"bu-member-connector"},"tasks":[{"connector":"bu-member-connector","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/catalog-connector
{"name":"catalog-connector","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.138.130","database.port":"5575","database.user":"root","database.password":"SQL@ynzy2020","database.server.id":"138130","database.server.name":"cms_management","database.whitelist":"cms_management","table.whitelist":"cms_management.tb_catalog","database.history.kafka.bootstrap.servers":"10.97.138.195:9092","database.history.kafka.topic":"cms_management.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"catalog-connector"},"tasks":[{"connector":"catalog-connector","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/cms-connector-es
{"name":"cms-connector-es","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.138.130","database.port":"5575","database.user":"root","database.password":"SQL@ynzy2020","database.server.id":"1301302","database.server.name":"cms","database.whitelist":"cms_management","table.whitelist":"cms_management.tb_init_article","database.history.kafka.bootstrap.servers":"10.97.138.195:9092 ","database.history.kafka.topic":"mxj.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"cms-connector-es"},"tasks":[{"connector":"cms-connector-es","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/org-info-connector
{"name":"org-info-connector","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.149.9","database.port":"5575","database.user":"root","database.password":"Mysql@ynzy2021","database.server.id":"149902","database.server.name":"db_zy_manager","database.whitelist":"db_zy_manager","table.whitelist":"db_zy_manager.tb_manager_org_info","database.history.kafka.bootstrap.servers":"10.97.138.195:9092","database.history.kafka.topic":"org-info.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"org-info-connector"},"tasks":[{"connector":"org-info-connector","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/lcy1-tb_entity_test
{"name":"lcy1-tb_entity_test","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.138.195","database.port":"3306","database.user":"root","database.password":"I.lw@2020","database.server.id":"1044","database.server.name":"lcy1","database.whitelist":"db_entities_relations","table.whitelist":"db_entities_relations.tb_entity_test","database.history.kafka.bootstrap.servers":"10.97.138.195:9092","database.history.kafka.topic":"lcy1_tb_entity_test.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","database.history.store.only.monitored.tables.ddl":"true","database.history.skip.unparseable.ddl":"true","name":"lcy1-tb_entity_test"},"tasks":[{"connector":"lcy1-tb_entity_test","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/mysql
{"name":"mysql","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","bigint.unsigned.handling.mode":"long","database.user":"root","database.server.id":"11","database.history.kafka.bootstrap.servers":"10.97.138.195:9092 ","database.history.kafka.topic":"history.zy","time.precision.mode":"connect","database.server.name":"debe","include.schema.changes":"true","database.port":"3306","max.request.size":"50000000","decimal.handling.mode":"string","database.hostname":"10.97.138.195","database.password":"I.lw@2020","name":"mysql","database.whitelist":"cdc_zy,db_entities_relations"},"tasks":[{"connector":"mysql","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/mxj-er-tie
{"name":"mxj-er-tie","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.149.9","database.port":"5575","database.user":"root","database.password":"Mysql@ynzy2021","database.server.id":"149911","database.server.name":"mxj","database.whitelist":"db_entities_relations","table.whitelist":"db_entities_relations.tb_init_entity","database.history.kafka.bootstrap.servers":"10.97.138.195:9092 ","database.history.kafka.topic":"mxj-tie.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"mxj-er-tie"},"tasks":[{"connector":"mxj-er-tie","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/mxj-connector
{"name":"mxj-connector","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.138.130","database.port":"5575","database.user":"root","database.password":"SQL@ynzy2020","database.server.id":"111","database.server.name":"mxj","database.whitelist":"cms_management","table.whitelist":"cms_management.tb_contribution","database.history.kafka.bootstrap.servers":"10.97.138.195:9092 ","database.history.kafka.topic":"mxj.history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"mxj-connector"},"tasks":[{"connector":"mxj-connector","task":0}],"type":"source"}[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]#
[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/u-member-sponsor-connector
{"error_code":404,"message":"Connector u-member-sponsor-connector not found"}[root@localhost kafka]# curl -X GET http://10.97.138.195:8083/connectors/bu-member-sponsor-connector
{"name":"bu-member-sponsor-connector","config":{"connector.class":"io.debezium.connector.mysql.MySqlConnector","database.hostname":"10.97.149.9","database.port":"5575","database.user":"root","database.password":"Mysql@ynzy2021","database.server.id":"130137","database.server.name":"mem_cdc","database.whitelist":"db_mem_sponsor","table.whitelist":"db_mem_sponsor.tb_sponsor_info","database.history.kafka.bootstrap.servers":"10.97.138.195:9092","database.history.kafka.topic":"mem_cdc.member_database_history","include.schema.changes":"true","decimal.handling.mode":"string","database.serverTimezone":"UTC","bigint.unsigned.handling.mode":"long","max.request.size":"50000000","time.precision.mode":"connect","name":"bu-member-sponsor-connector"},"tasks":[{"connector":"bu-member-sponsor-connector","task":0}],"type":"source"}[root@localhost kafka]#


#新的需求
debe.db_entity_relations.tb_entity
debe.db_entity_relations.tb_entity_relation


[root@localhost props]# cat mysql.properties
name=mysql
connector.class=io.debezium.connector.mysql.MySqlConnector
database.hostname=10.97.138.195
database.port=3306
database.user=root
database.password=I.lw@2020
database.server.id=11
database.server.name=debe
database.whitelist=cdc_zy,db_entities_relations
database.history.kafka.bootstrap.servers=10.97.138.195:9092
database.history.kafka.topic=history.zy
include.schema.changes=true
#inconsistent.schema.handling.mode=warn
# options: adaptive_time_microseconds（default）adaptive(deprecated) connect()
time.precision.mode=connect
# options: precise(default) double string
decimal.handling.mode=string
# options: long(default) precise
bigint.unsigned.handling.mode=long
max.request.size=50000000

curl -i http://10.97.138.195:8083/connectors -X POST -H "Content-Type: application/json" --data '{"name":"db_entity_relations.Oyrl","config":{"connector.class": "io.debezium.connector.mysql.MySqlConnector","database.hostname": "10.97.138.195","database.port": "3306","database.user": "root","database.password": "I.lw@2020","database.server.id": "11","database.server.name": "debe","database.whitelist": "cdc_zy,db_entities_relations","database.history.kafka.bootstrap.servers": "10.97.138.195:9092","database.history.kafka.topic": "history.zy","include.schema.changes": "true","decimal.handling.mode": "string","database.serverTimezone": "UTC","bigint.unsigned.handling.mode": "long","max.request.size": "50000000","time.precision.mode": "connect","database.history.store.only.monitored.tables.ddl":"true","database.history.skip.unparseable.ddl":"true","name": "db_entity_relations.Oyrl","producer.override.max.request.size": "52428800","broker.override.message.max.bytes": "52428800","consumer.override.fetch.message.max.bytes": "52428800"}}'