kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs" # 与 storageclass.yaml 中的 name 一致
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi