---
- name: init 4.0 conf
  template:
    src: redis-4.0.conf.j2
    dest: "{{ redis_conf_dir }}/redis-{{ redis_port }}.conf"
    mode: '0644'
  tags: init_redis_conf
  when:  redis_version[0:1] == "4"

- name: init 3.2 conf
  template:
    src: redis-3.2.conf.j2
    dest: "{{ redis_conf_dir }}/redis-{{ redis_port }}.conf"
    mode: '0644'
  tags: init_redis_conf
  when:  redis_version[0:1] == "3"

- name: init 5.0 conf
  template:
    src: redis-5.0.conf.j2
    dest: "{{ redis_conf_dir }}/redis-{{ redis_port }}.conf"
    mode: '0644'
  tags: init_redis_conf
  when:  redis_version[0:1] == "5"
