---
- name: Upload  Extend Package
  copy:
    src: "ext/{{ extend_package }}"
    dest: "{{ php56_ext_src_dir }}"
    mode: "0755"
    remote_src: no
  loop:
    - "geoip-1.1.1.tgz"
    - "libevent-2.0.22-stable.tar.gz"
    - "memcache-2.2.7.tgz"
    - "redis-2.2.8.tgz"
    - "swoole-1.8.3.tgz"
    - "xhprof-0.9.4.tgz"
    - "imagick-3.4.3.tgz"
    - "libmemcached-1.0.18.tar.gz"
    - "memcached-2.2.0.tgz"
    - "sphinx-1.3.3.tgz"
    - "varnish-1.2.1.tgz"
    - "zendopcache-7.0.5.tgz"
  loop_control:
    loop_var: extend_package

- name: Upload  Install Package
  copy:
    src: "{{ install_package }}"
    dest: "{{ php56_src_dir }}"
    mode: "0755"
    remote_src: no
  loop:
    - "php-5.6.40.tar.gz"
    - "ImageMagick-6.9.6-8.tar"
  loop_control:
    loop_var: install_package

- name: Upload  Install Script
  copy:
    src: "scripts/{{ install_script }}"
    dest: "{{ php56_script_dir }}"
    mode: "0755"
    remote_src: no
  loop:
    - "imagemagick.sh"
    - "php-install.sh"
    - "libiconv.sh"
    - "phpext-imagick.sh"
    - "phpext-memcache.sh"
    - "libevent.sh"
    - "libmemcache.sh"
    - "phpext-memcached.sh"
    - "phpext-redis.sh"
  loop_control:
    loop_var: install_script 

- name: Install Script
  shell: |
    cd "{{ php56_script_dir }}"
    /bin/sh php-install.sh 5.6.40
    /bin/sh imagemagick.sh 6.9.6-8
    /bin/sh libevent.sh 2.0.22
    /bin/sh libmemcache.sh 1.0.18
    /bin/sh phpext-imagick.sh 3.4.3
    /bin/sh phpext-memcache.sh 2.2.7
    /bin/sh phpext-memcached.sh 2.2.0
    /bin/sh phpext-redis.sh 2.2.8