---
- name: Init Directiory
  file:
    path: "{{ php56_dir }}"
    state: directory
  loop:
    - "{{ php56_ext_src_dir }}"
    - "{{ php56_script_dir }}"
  loop_control:
    loop_var: php56_dir

- include_tasks: C7_{{ item }}.yml
  with_items:
    #- PHP56_Install
    - PHP56_Init_Conf
  when:
    - ansible_distribution_major_version == "7"
    
