#### zookeeper ####
# zk 源文件目录
zk_src_dir: "{{ src_dir }}/apache-zookeeper-{{ zk_version }}-bin"
# zk 安装变量
zk_install_dir: '/usr/local/apache-zookeeper-{{ zk_version }}-bin'
zk_data_dir: "{{ zk_install_dir}}/data"
zk_conf_dir: "{{ zk_install_dir}}/conf"
zk_bin_dir: "{{ zk_install_dir}}/bin"
zk_logs_dir: "{{ zk_install_dir}}/logs"
zk_port: 2181 

zk_hostip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
zk_version: "3.5.9"
zk_remote_down: "https://downloads.apache.org/zookeeper/zookeeper-{{ zk_version }}/apache-zookeeper-{{ zk_version }}-bin.tar.gz"

# zk cluster
zk_cluster: [["1","192.168.12.221"],["2","192.168.12.222"],["3","192.168.12.223"]]