php_install_dir : "/usr/local/php74"
php_conf_dir : "{{ php_install_dir }}/etc"
php74_start_script: "/etc/init.d/php-fpm-74"
tnginx_conf_dir : "/usr/local/tnginx-2.3.2/conf/sites"
tnginx_install_dir: "/usr/local/tnginx-2.3.2/"
yum_repo : "https://mirrors.tuna.tsinghua.edu.cn/zabbix/zabbix/5.4/rhel/8"
zabbix_serverip : "10.15.205.93"
zabbix_db : "zabbix"
zabbix_db_user : "zabbix"
zabbix_db_password : "123456"
mysql_bin_dir : "/usr/local/mysql57/bin"