
- name: init directiory
  file:
    path: "{{ tomcat_dir }}"
    state: directory
  loop:
    - "{{ tomcat_src_dir }}"
  loop_control:
    loop_var: tomcat_dir


- name: upload tomcat src
  copy:
    src: "apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_src_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    mode: "0755"
    remote_src: no

- name: install tomcat
  shell: |
    cd "{{ tomcat_src_dir }}"
    tar xf apache-tomcat-"{{ tomcat_version }}".tar.gz
    mv apache-tomcat-"{{ tomcat_version }}" /usr/local/tomcat-"{{ tomcat_version }}"